### ISSUE TITLE
Erros in terminal.

### ISSUE THREAD

**Issue by highacid** [bhilburn/powerlevel9k#297]
prompt_dir:4: character not in range
right_prompt_segment:32: command not found: print_icon
right_prompt_segment:38: command not found: print_icon
right_prompt_segment:32: command not found: print_icon
right_prompt_segment:32: command not found: print_icon
prompt_dir:4: character not in range                                                                                                                        1705  15:21:14
right_prompt_segment:32: command not found: print_icon
right_prompt_segment:38: command not found: print_icon
right_prompt_segment:32: command not found: print_icon
right_prompt_segment:32: command not found: print_icon

**Comment by bhilburn** [comment]
Hi @highacid -

Can you provide more information to help us debug the problem? What is your PL9k configuration? How are you using it (stand-alone or in a framework?)? How did you install the fonts?

**Comment by highacid** [comment]
I fixed the issue, it can be closed. Thanks

**Comment by Zaydme** [comment]
for anyone still having this problem do `locale -a`
```
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_COLLATE to default locale: No such file or directory
C
POSIX
```
if you had the same output as above, then you have to enable a locale that supports **UTF-8**

simply edit `/etc/locale.gen` and uncomment a **UTF-8** locale, for me I uncommented `en_US.UTF-8`
and then run `sudo locale-gen` and reopen the terminal emulator. 
everything should work fine hopefully
