### ISSUE TITLE
Dealing with `awesome-fontconfig` codepoints

### ISSUE THREAD

**Issue by bhilburn** [bhilburn/powerlevel9k#382]
Okay, it looks like we might have a code-point issue with some "awesome" fonts.

While doing some testing recently, I switched over to `awesome-fontconfig` and the `OK_ICON` was actually the [medium.com](medium.com) logo. I'm not the only person it impacted - as an example, check out this bug report that just got filed, #375, and note that where there should be a checkmark there is actually the medium.com logo.

Per @V1rgul's comment, here, though, on his font the other icons were preferrable:
https://github.com/bhilburn/powerlevel9k/commit/95f0c3c6ecd2fc1edfd1b768150237d682426890#commitcomment-20573173

Need to do some digging. I suspect that the solution is going to be that some people need to put manual overrides for certain ICONs in their configs. Not a huge deal, but it is an additional step, so we should try to make it work for as many people as possible out-of-the-box.

It would be great if more people could comment, here, on whether or not the old way or the new way is better for them. **Please also describe how you installed your fonts, which font you are using, and which PL9k you are using.**

@/all
@V1rgul @dritter @rjorgenson @Tritlo @ryanoasis @lcorsini

**Comment by V1rgul** [comment]
my configuration came from here: https://github.com/gabrielelana/awesome-terminal-fonts
The fonts were updated 23/07/2016. I updated mine, and the Medium logo was showing before your commits.
We might want to track the awesome-terminal-fonts repository to avoid these problems :)

This file can help seeing all the available icons when cat in the terminal: https://gist.github.com/V1rgul/73810cbf4f8227b37749fb18fa1e9304

**Comment by bhilburn** [comment]
@V1rgul - That would be great, actually, if you could file a PR.

**Comment by lcorsini** [comment]
Got the same issue using nerd-fonts, since they patch fonts with various sources, codepoints are messed up if I use awesome-fontconfig, so I made a fork in november, I think, which overrides these fonts:
![capture_fonts](https://cloud.githubusercontent.com/assets/1501930/22243885/9865d7a4-e229-11e6-9add-b78eb007b6ce.JPG)

**Comment by varunagrawal** [comment]
I tried using the master and patched branches of `awesome-terminal-fonts`, and the former gave me the Medium logo instead of the check mark, whereas the latter gave me a greek symbol where the github octocat should have been.
I picked up the config from the `awesome-terminal-fonts` repo and the default version as well as setting the family to `SourceCodePro` has no effect (documentation is vague there though, if we can figure this out, I'd be glad to help write up the docs).
In both cases I had to install the `PowerlineSymbols.otf` file to get the powerline train arrows showing. 

Trying `nerd-fonts` also didn't seem to help.

**Comment by V1rgul** [comment]
Did you try https://github.com/bhilburn/powerlevel9k/pull/385 ?
It should fix the issues of different versions of `awesome-terminal-fonts`

**Comment by varunagrawal** [comment]
@V1rgul I'll try it out. However, doesn't the master plan state that PL9K will go with nerd-fonts? I'd really like to see that happen at the earliest!

**Comment by varunagrawal** [comment]
@V1rgul I tried out your updated version and I am still getting the issues with the icons when using the patched version of awesome-terminal-fonts. Moreover, I still seem to need PowerlineSymbols.otf (which is Option 2) in order to get the powerline train to render correctly.
This is disconcerting since the installation instructions make it seem that I only require `awesome-terminal-fonts` to be installed to get everything working.

**Comment by V1rgul** [comment]
@varunagrawal My pull request only fixes the `awesome-fonconfig` version
And yes, `PowerlineSymbols` are needed to have the "arrow" segment separators

**Comment by varunagrawal** [comment]
@V1rgul sorry about that. Just reconfigured my zshrc and yes everything works as expected! :smile: 
I can see what you mean when you prefer the larger check mark.

**Comment by bhilburn** [comment]
Closing this to carry on the conversation elsewhere.
