### ISSUE TITLE
VCS segment: Git branch name not always accurate

### ISSUE THREAD

**Issue by julienfalque** [bhilburn/powerlevel9k#786]
I noticed that sometimes, for Git repositories, the VCS segment shows a different branch name than the one I actually checked out. Here is an example I got:

```
 julien > ~/Projects/some-project > remotes/origin/a-random-branch >
 $ git status
HEAD detached at origin/release_1.0
nothing to commit, working tree clean
```

As you can see, I checked out `origin/release_1.0` but the segment shows I am on branch `origin/a-random-branch`.

I think this mostly happens when checking out remote branches rather than local ones, or maybe when they point to the same commit.

**Comment by bhilburn** [comment]
Hm, that's strange. So, in what you copy / pasted, it looks like you've checked out a remote branch, but don't have a local copy, so what you actually did is move into a detached HEAD state and move to an arbitrary commit (which happens to have a branch pointer on the remote). What's strange to me is that `a-random-branch` exists as a string, and you don't just see a commit hash.

What is `a-random-branch` usually? Is it a branch name you've actually created?

**Comment by dritter** [comment]
@julienfalque Could you paste the output of `echo ${${$(git rev-parse --verify HEAD@{upstream} --symbolic-full-name 2>/dev/null)/refs\/(remotes|heads)\/}#*/}` and `git symbolic-ref --short HEAD 2>/dev/null`. It seems like you see the remote branch only..

**Comment by julienfalque** [comment]
@bhilburn I used `a-random-branch` as a replacement of the actual branch name that was shown. The actual branch was a remote one created on `origin` by someone else.

@dritter Unfortunately I changed branches on the repo where I got the issue since I reported it. But I was able to have a similar issue on another repository. On this project, I have two remotes: `upstream` (the main GitHub repository) and `origin` (my GitHub fork).

```console
 julien > ~/Projects/Personal/php-cs-fixer > remotes/upstream/master >
 $ git checkout origin/master                                                                                      
Previous HEAD position was c1a3c201 bumped version
HEAD is now at 0b21f6f2 Merge branch '1.12'

 julien > ~/Projects/Personal/php-cs-fixer > remotes/origin/HEAD >
 $ echo ${${$(git rev-parse --verify HEAD@{upstream} --symbolic-full-name 2>/dev/null)/refs\/(remotes|heads)\/}#*/}


 julien > ~/Projects/Personal/php-cs-fixer > remotes/origin/HEAD >
 $ git symbolic-ref --short HEAD 2>/dev/null

 julien > ~/Projects/Personal/php-cs-fixer > remotes/origin/HEAD >
 $ 
```

As you can see, I first checked out `upstream/master` and the VCS segment showed the expected branch name. Then I checked out `origin/master` and the VCS segment showed `remotes/origin/HEAD` while I expected `remotes/origin/master`. The command you provided didn't seem to output anything.

**Comment by bhilburn** [comment]
Let's circle back around to this and try to get it resolved in the `next` codebase.

@julienfalque - Can you grab the current `next` branch and let us know if you are still seeing this issue? If so, I'm sure this is some git-foo we've mucked up somewhere. Hopefully it's an easy fix.

**Comment by bhilburn** [comment]
Any chance this was just fixed by the merge of #941 into `next`?

**Comment by julienfalque** [comment]
I just checked with the `next` branch but unfortunately the bug still occurs.

**Comment by bhilburn** [comment]
Okay, I'm super confused about this.

@julienfalque - Can you reproduce using the `next` branch, and then also show us a list of the local branches and the remotes? I think there is something weird happening here with detached states in git.

**Comment by julienfalque** [comment]
I just tried with the `next` branch (`45079e1`) using a fresh clone and I still have the issue:

```
$ git clone git@github.com:julienfalque/PHP-CS-Fixer.git TEST && cd TEST
# -> master

$ git remote add --fetch upstream git@github.com:FriendsOfPHP/PHP-CS-Fixer.git
# -> master

$ git checkout origin/master
# -> heads/master

$ git checkout upstream/master
# -> remotes/upstream/master

$ git checkout origin/master
# -> heads/master

$ git branch -a 
* (HEAD detached at origin/master)
  master
  remotes/origin/HEAD -> origin/master
  remotes/origin/braces-preserve-empty-lines
  remotes/origin/console-deprecation-warnings
  remotes/origin/doc
  remotes/origin/fix-array-indentation-with-multiline-ternary
  remotes/origin/for-spaces
  remotes/origin/master
  remotes/origin/multiline-whitespace-before-comma-fixer
  remotes/origin/psr-5-inheritdoc
  remotes/origin/variable-variables-fixer
  remotes/upstream/2.12
  remotes/upstream/2.13
  remotes/upstream/3.0
  remotes/upstream/master
```

As you can see, when I checkout `origin/master`, the segment shows `heads/master` instead of the expected `remotes/origin/master`.

**Comment by bhilburn** [comment]
@julienfalque - Yup, I see what you're describing. Looking at the output, though, it looks to me like what P9k is reporting to you is actually *correct*. Per the output of `git branch -a`, you really are in a detached HEAD state, pointing to the same commit as `origin/master`. Based on some stackoverflow posts, this is expected if you check out a branch that is remote-only (i.e., you don't have a local branch pointer) - this makes sense.

What doesn't make sense to me is why it's not doing this for the `remotes/upstream/master` case. Can you checkout `remotes/upstream/master` and then do `git branch -avv`?

**Comment by julienfalque** [comment]
```
$ git checkout origin/master
# segment shows branch "heads/master"

$ git status
HEAD detached at origin/master

$ git branch -a
* (HEAD detached at origin/master)
  master
  remotes/origin/HEAD -> origin/master
  remotes/origin/braces-preserve-empty-lines
  remotes/origin/console-deprecation-warnings
  remotes/origin/doc
  remotes/origin/fix-array-indentation-with-multiline-ternary
  remotes/origin/for-spaces
  remotes/origin/master
  remotes/origin/multiline-whitespace-before-comma-fixer
  remotes/origin/psr-5-inheritdoc
  remotes/origin/variable-variables-fixer
  remotes/upstream/2.12
  remotes/upstream/2.13
  remotes/upstream/3.0
  remotes/upstream/master

$ git checkout upstream/master
# segment shows branch "remotes/upstream/master"

$ git status
HEAD detached at upstream/master

$ git branch -a
* (HEAD detached at upstream/master)
  master
  remotes/origin/HEAD -> origin/master
  remotes/origin/braces-preserve-empty-lines
  remotes/origin/console-deprecation-warnings
  remotes/origin/doc
  remotes/origin/fix-array-indentation-with-multiline-ternary
  remotes/origin/for-spaces
  remotes/origin/master
  remotes/origin/multiline-whitespace-before-comma-fixer
  remotes/origin/psr-5-inheritdoc
  remotes/origin/variable-variables-fixer
  remotes/upstream/2.12
  remotes/upstream/2.13
  remotes/upstream/3.0
  remotes/upstream/master
```

For both `upstream/master` and `origin/master` remote branches I don't have a local tracking branch and `git status` shows I'm in detached HEAD state at `upstream/master` or `origin/master` so for both branches I would expect the segment to show the exact branch name rather than `heads/master` which is confusing IMO.

Maybe the difference comes from this line from `git branch -a`:
```
remotes/origin/HEAD -> origin/master
```

**Comment by bhilburn** [comment]
I am on a issue-cleaning spree. This issue hasn't had motion in quite some time, and so I am closing it out due to inactivity. If anyone would like to re-open it because they feel it is un-resolved and is something they care about, please feel free to re-raise the discussion!
